### PR TITLE
Deceptive dinos fossil multiplier hack

### PR DESCRIPTION
**Pull request by qaiik**
First of all, I'm sorry that lol-jude over here has been stealing your hacks. I did multiple things and even hacked his repo for a short amount of time.

I decided to help by making a pr with a new hack for deceptive dinos called setFossilMult.js because I know how to make blooket hacks and I have my own repo of them.
It does what it sounds like. It asks you what fossil multiplier you want and sets your current fossil multiplier to that.

I kept your credit and made it confirm to join your discord when it errors, although your link in your hacks doesn't work.

### CODE REVIEW

**Comment by therealgliz** [comment]
I appreciate it but I'm not looking to update this repo.

**Comment by qaiik** [comment]
Ok. I understand.  I would be up for maintaining it if you ever decide to give it away.

**Comment by VillainsRule4000** [comment]
@qaiik
1. Don't forget to make the qaiik.github.io repo.
2. Ask acai about @therealgliz.

**Comment by notzastix** [comment]
> @qaiik
> 
>     1. Don't forget to make the qaiik.github.io repo.
> 
>     2. Ask acai about @therealgliz.

ask acai about what?

**Comment by VillainsRule4000** [comment]
@notzastix Just DM him and ask him about @therealgliz...

**Pull request closed without merging**
